doc: HACK: Move the docs under doc/ so that we can build
Otherwise, I get this on install:

NotADirectoryError: [Errno 20] Not a directory: '/home/anholt/src/xserver/build/xserver-doc/html/assets/js/search/hotdoc_fragments/../hw/xfree86'

Signed-off-by: Eric Anholt <eric@anholt.net>