include: xkbstr.h: fix missing include of Xdefs.h
xkbstr.h uses types from Xdefs.h (eg. Bool) but doesn't include it.
If somebody includes it, w/o including Xdefs.h first, compile breaks:

../include/xkbstr.h:84:5: error: unknown type name ‘Bool’
   84 |     Bool active;
      |     ^~~~
../include/xkbstr.h:517:5: error: unknown type name ‘Bool’
  517 |     Bool num_groups_changed;
      |     ^~~~
../include/xkbstr.h:608:5: error: unknown type name ‘Bool’
  608 |     Bool has_own_state;
      |     ^~~~

Signed-off-by: Enrico Weigelt, metux IT consult <info@metux.net>
Part-of: <https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/1474>